services:
  postgres:
    image: postgres:17
    container_name: games_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: games_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - ontop-demo-network

  ontop-vkg:
    image: ontop/ontop:latest
    container_name: ontop-vkg
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./ontop/input:/opt/ontop/input
      - ./ontop/jdbc:/opt/ontop/jdbc
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ontology.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mappings.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ontop.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_LAZY_INIT: "true"
      ONTOP_DEV_MODE: "false"
    networks:
      - ontop-demo-network

networks:
  ontop-demo-network:
    driver: bridge

volumes:
  db_data: